server:
  port: 8080
  tomcat:
    max-threads: 10
  session-timeout: 7200
  
logging:
  config: classpath:logback.xml
  
datasource:
  mysql:
    url: jdbc:mysql://120.26.75.31:3306/racingdb
    username: root
    password: leonRemoteDB
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    maxActive: 50
    maxWait: -1
    minIdle: 5
    validationQuery: select 1 from DUAL